# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Juan Pablo Berrizbeitia
tagline:          'JPBerriz'
description: >      
   Building a creative practice
   @jpberriz
url:              https://jpberriz.com
baseurl:          /

author:
  name:           'Juan Pablo Berrizbeitia'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
