# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            JPBerriz
tagline:          'Building a creative practice'
description:      'Working on NonProfit Business Management. Teaching Innovation. Thinking how to re-Design Justice. Learning Aikido. Playing with my guitar'
url:              https://jpberriz.com
baseurl:          /

author:
  name:           'Juan Pablo Berrizbeitia'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
