# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Juan Pablo Berrizbeitia
tagline:          'JPBerriz'
description:      'Building a creative practice'
url:              https://jpberriz.com
baseurl:          /

author:           'Juan Pablo Berrizbeitia'
  name:           'Juan Pablo Berrizbeitia'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

include:          ['_pages']

tipue_search:
  include:
    pages:        true
